server.port=8090
spring.application.name=web-ui

# URL base del gateway
gateway.base-url=http://localhost:8080

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always



